[profile.default]
solc_version = "0.8.26"
evm_version = "cancun"
via_ir = true

optimizer = true
optimizer_runs = 9_999_999

remappings = [
  "@solady=lib/solady/",
  "@forge=lib/forge-std/src/"
]

[fmt]
line_length = 100

[rpc_endpoints]
base = "https://rpc.ankr.com/base"