// SPDX-License-Identifier: AGPL-3.0-only
pragma solidity ^0.8.19;

contract Section2 {
    function section2() public pure returns (string memory) {
        return string(
            abi.encodePacked(
                '<h2 class="section">2. Definitions</h2>',
                '<p class="legal-text">"Capital Stock" means the capital stock of the Company, including, without limitation, the "Common Stock" and the "Preferred Stock."</p>',
                '<p class="legal-text">"Change of Control" means (i) a transaction or series of related transactions in which any "person" or "group" (within the meaning of Section 13(d) and 14(d) of the Securities Exchange Act of 1934, as amended), becomes the "beneficial owner" (as defined in Rule 13d-3 under the Securities Exchange Act of 1934, as amended), directly or indirectly, of more than 50% of the outstanding voting securities of the Company having the right to vote for the election of members of the Company\'s board of directors, (ii) any reorganization, merger or consolidation of the Company, other than a transaction or series of related transactions in which the holders of the voting securities of the Company outstanding immediately prior to such transaction or series of related transactions retain, immediately after such transaction or series of related transactions, at least a majority of the total voting power represented by the outstanding voting securities of the Company or such other surviving or resulting entity or (iii) a sale, lease or other disposition of all or substantially all of the assets of the Company.</p>',
                '<p class="legal-text">"Company Capitalization" is calculated as of immediately prior to the Equity Financing and (without double-counting): Includes all shares of Capital Stock issued and outstanding; Includes all Converting Securities; Includes all (i) issued and outstanding Options and (ii) Promised Options; and Includes the Unissued Option Pool, except that any increase to the Unissued Option Pool in connection with the Equity Financing shall only be included to the extent that the number of Promised Options exceeds the Unissued Option Pool prior to such increase.</p>',
                '<p class="legal-text">"Converting Securities" includes this Safe and other convertible securities issued by the Company, including but not limited to: (i) other Safes; (ii) convertible promissory notes and other convertible debt instruments; and (iii) convertible securities that have the right to convert into shares of Capital Stock.</p>',
                '<p class="legal-text">"Direct Listing" means the Company\'s initial listing of its Common Stock (other than shares of Common Stock not eligible for resale under Rule 144 under the Securities Act) on a national securities exchange by means of an effective registration statement on Form S-1 filed by the Company with the SEC that registers shares of existing capital stock of the Company for resale, as approved by the Company\'s board of directors. For the avoidance of doubt, a Direct Listing shall not be deemed to be an underwritten offering and shall not involve any underwriting services.</p>',
                '<p class="legal-text">"Dissolution Event" means (i) a voluntary termination of operations, (ii) a general assignment for the benefit of the Company\'s creditors or (iii) any other liquidation, dissolution or winding up of the Company (excluding a Liquidity Event), whether voluntary or involuntary.</p>',
                '<p class="legal-text">"Equity Financing" means a bona fide transaction or series of transactions with the principal purpose of raising capital, pursuant to which the Company issues and sells Preferred Stock at a fixed valuation, including but not limited to, a pre-money or post-money valuation.</p>',
                '<p class="legal-text">"Initial Public Offering" means the closing of the Company\'s first firm commitment underwritten initial public offering of Common Stock pursuant to a registration statement filed under the Securities Act.</p>',
                '<p class="legal-text">"Liquidity Capitalization" is calculated as of immediately prior to the Liquidity Event, and (without double-counting): Includes all shares of Capital Stock issued and outstanding; Includes all (i) issued and outstanding Options and (ii) to the extent receiving Proceeds, Promised Options; Includes all Converting Securities, other than any Safes and other convertible securities (including without limitation shares of Preferred Stock) where the holders of such securities are receiving Cash-Out Amounts or similar liquidation preference payments in lieu of Conversion Amounts or similar "as-converted" payments; and Excludes the Unissued Option Pool.</p>',
                '<p class="legal-text">"Liquidity Event" means a Change of Control, a Direct Listing or an Initial Public Offering.</p>',
                '<p class="legal-text">"Liquidity Price" means the price per share equal to the Post-Money Valuation Cap divided by the Liquidity Capitalization.</p>',
                '<p class="legal-text">"Options" includes options, restricted stock awards or purchases, RSUs, SARs, warrants or similar securities, vested or unvested.</p>',
                '<p class="legal-text">"Proceeds" means cash and other assets (including without limitation stock consideration) that are proceeds from the Liquidity Event or the Dissolution Event, as applicable, and legally available for distribution.</p>',
                '<p class="legal-text">"Promised Options" means promised but ungranted Options that are the greater of those (i) promised pursuant to agreements or understandings made prior to the execution of, or in connection with, the term sheet or letter of intent for the Equity Financing or Liquidity Event, as applicable (or the initial closing of the Equity Financing or consummation of the Liquidity Event, if there is no term sheet or letter of intent), (ii) in the case of an Equity Financing, treated as outstanding Options in the calculation of the Standard Preferred Stock\'s price per share, or (iii) in the case of a Liquidity Event, treated as outstanding Options in the calculation of the distribution of the Proceeds.</p>',
                '<p class="legal-text">"Safe" means an instrument containing a future right to shares of Capital Stock, similar in form and content to this instrument, purchased by investors for the purpose of funding the Company\'s business operations. References to "this Safe" mean this specific instrument.</p>',
                '<p class="legal-text">"Safe Preferred Stock" means the shares of the series of Preferred Stock issued to the Investor in an Equity Financing, having the identical rights, privileges, preferences and restrictions as the shares of Standard Preferred Stock, other than with respect to: (i) the per share liquidation preference and the initial conversion price for purposes of price-based anti-dilution protection, which will equal the Safe Price; and (ii) the basis for any dividend rights, which will be based on the Safe Price.</p>',
                '<p class="legal-text">"Safe Price" means the price per share equal to the Post-Money Valuation Cap divided by the Company Capitalization.</p>',
                '<p class="legal-text">"Standard Preferred Stock" means the shares of the series of Preferred Stock issued to the investors investing new money in the Company in connection with the initial closing of the Equity Financing.</p>',
                '<p class="legal-text">"Unissued Option Pool" means all shares of Capital Stock that are reserved, available for future grant and not subject to any outstanding Options or Promised Options (but in the case of a Liquidity Event, only to the extent Proceeds are payable on such Promised Options) under any equity incentive or similar Company plan.</p>'
            )
        );
    }
}
